load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mediapipe_object_tracking",
    calculators = ["//mediapipe/graphs/tracking:mobile_calculators"],
)
